### ISSUE TITLE
Graphene-spline example broken

### ISSUE THREAD

**Issue by ondrejkrejci** [ProkopHapala/ProbeParticleModel#74]
The example is broken in 2 places:
The most important while running this:
`python3 ../../relaxed_scan.py -k 0.5 -q -0.00 --tipspline TipRSpline.ini`
it has this error:
```
Traceback (most recent call last):
  File "../../relaxed_scan.py", line 139, in <module>
    fzs,PPpos,PPdisp,lvecScan=PPH.perform_relaxation(lvec, FFLJ, FFel, FFboltz,options.tipspline)
  File "/m/home/home8/88/krejcio1/unix/Program_Files/PPAFM_main/ppafm/HighLevel.py", line 102, in perform_relaxation
    FF += FFboltz
```

The 2nd problem is connected with **npy** and #53 ; in Pull Request #73 commented out temporatily!

**Comment by yakutovicha** [comment]
We will delete this functionality together with the example.
