### ISSUE TITLE
Python 3 nPBC problem

### ISSUE THREAD

**Issue by JackHenry281** [ProkopHapala/ProbeParticleModel#9]
Hi,

I have been trying the new python 3 version of the PPM. I am getting an error when I manually set the nPBC value. The error occurs for my own PPM simulation using a cube file, and with the graphene example given.

In the Graphene example if I set 'nPBC    0 0 0' I get the error message
' Traceback (most recent call last):
  File "../../generateLJFF.py", line 82, in <module>
    xsfHead=basUtils.bas2xsf(iZs,Rs,PPU.params['nPBC'] if PBC else [0,0,0] )
  File "/mnt/t/+PPM_P3_their/pyProbeParticle/basUtils.py", line 286, in bas2xsf
    header2+=str(iZs[ia])+' '+str(Rs[ia][0])+' '+str(Rs[ia][1])+' '+str(Rs[ia][2])+' \n'
IndexError: index 71 is out of bounds for axis 0 with size 71'.

I have looked in the code but can't figure out how to fix this issue. The issue does not happen if I leave nPBC undefined, which should result in it being autoset to 0 0 0.

Would you also be able to clarify for me what the nPBC and PBC parameters do?

Thanks, Jack

**Comment by ondrejkrejci** [comment]
Hi Jack,

I'm sorry this is my mistake, which happened, when I tried quickly program putting atoms into FFLJ_z.xsf file. 

I'll look at that this week. and will try to repair it. 
Anyway we agree, that PBC & nPBC options are a puzzling issue, but we haven't find a better way how to describe it:
Well, from the principle the code works, your basic cell is always periodic. You have your 3D voxelized forces and if you move outside of the original box, you always fold to the original box. There is no other way how to make the code using pre-calculated force-fields. 
PBC & nPBC is affecting only the calculations of Lennard-Jones force-field:
So, PBC False === nPBC 0 0 0 -- means - you use only geometry of the original cell. It is useful only for molecules, that are super-far away from the border. 
nPBC 1 1 1 (default) - The last number play no-role. There original cell is 3x3 repeated, with the centre in the original cell. You then calculate your L-J potential & forces using this 9 cell - it is used standardly for most of the periodic structures like surfaces, graphene sheets ...
nPBC 2 2 1 - The last number play no-role. There original cell is 5x5 repeated, with the centre in the original cell. Used for really small cells.
nPBC 3 3 1 - The last number play no-role. There original cell is 7x7 repeated, with the centre in the original cell. Used for really super small cells.
....
I will fix this issue, hopefully tonight, or tomorrow. I hope, I at least explained to you the PBC and nPBC parameters, if not, please comment, I'll do my best to be more explicit.

Regards & thanks for finding this issue! Ondrej

**Comment by JackHenry281** [comment]
Hi Ondrej, 

Thanks for the detailed response, and thanks for looking at the issue. I have played around with the PBC and nPBC parameters and (thankfully) my understanding of the nPBC is what you just described. 

My understanding: nPBC[0] and nPBC[1] control the number of repeats of the unit cell taken in the X and Y directions into account when calculating the FFLJ matrices. The nPBC[2] parameter is always set to 0.

I wrote up my understanding of the nPBC parameter with a diagram, if you want I can send it to you for the wiki.

As for the PBC parameter, I am still a bit confused. Are you saying setting 'PBC    False' is equivalent to setting 'nPBC   0 0 0', and setting 'PBC    True' is equivalent to setting 'nPBC   1 1 1'?

**Comment by ondrejkrejci** [comment]
Hi,

just in fast:

1) you can send the image and explanation to my work email, if you wish ( ondrej(dot)krejci(at)aalto(dot)fi )
2) PBC False means nPBC 0 0 0 while PBC True means read nPBC (if they are not written in params.ini, then it is nPBC 1 1 1 by defaults )
Cheers,
Ondrej

**Comment by ondrejkrejci** [comment]
Hi,

sorry I didn't managed yesterday. I repaired and test everything few minutes ago. Now everything should work as I told you yesterday.
Please can you send me those things for wiki, if you have them? If you have some more questions, do not hesitate to write us.
Thank you!
Cheers,
Ondrej

**Comment by JackHenry281** [comment]
Hi, 

Thanks for fixing that so quickly. I had a look and everything seems to work now.

I've attached the diagram and caption which explain the nPBC parameter.

![nPBC_diagram](https://user-images.githubusercontent.com/46002710/77522976-fabe5880-6e7c-11ea-915a-87b2fa9a758d.png)

**Comment by ondrejkrejci** [comment]
Hi Jack!

Thank you, please have a look on the wiki, if you are happy now. Maybe you can tell us, where this is originally published. If you do not have any more comments, I will close the Issue by the end of this week.
Thank you once more.
Regards,
Ondrej

**Comment by JackHenry281** [comment]
Hi Ondrej,

The diagram is from the 1st year transfer report of my PhD. I wrote a section on the workings of the PPM and how the coordinate systems interact, as an introduction for future PPM users. I have also done work on simulated force minimum images using the PPM. My intention was to eventually share this work with you. When I get time to check the PPM sections of my report are safe to share (contains no important unpublished work) I'll send it over for you to look at. It might be a strong addition to the Wiki for new users.

I also made a few changes to the python2 code. The PPM was written to be quick at the cost of being less efficient with RAM usage. This became an issue for me when I was performing high resolution simulations, or simulating larger unit cells. I made a few very small changes to the order matrices were generated etc, and downgraded some matrices to float32 variables. This saved 50%+ of the RAM usage. If you are interested in merging these change with the master PPM code I'll send them over to you.

Hope all is well, Jack

**Comment by furuderika9** [comment]
> Hi Ondrej,
> 
> The diagram is from the 1st year transfer report of my PhD. I wrote a section on the workings of the PPM and how the coordinate systems interact, as an introduction for future PPM users. I have also done work on simulated force minimum images using the PPM. My intention was to eventually share this work with you. When I get time to check the PPM sections of my report are safe to share (contains no important unpublished work) I'll send it over for you to look at. It might be a strong addition to the Wiki for new users.
> 
> Hope all is well, Jack

Sorry to bother you, but can I have one copy of the introduction for PPM users? I have questions on the meaning of gridA/B/C and gridN.

**Comment by ondrejkrejci** [comment]
> Sorry to bother you, but can I have one copy of the introduction for PPM users? I have questions on the meaning of gridA/B/C and gridN.

Hello, as far as I know, there is no introduction to PPM. We have the [github wiki](https://github.com/ProkopHapala/ProbeParticleModel/wiki/Home/) and the original [nanosurf wiki](https://nanosurf.fzu.cz/wiki/doku.php?id=probe_particle_model). I agree that both are not ideal. Maybe we can use this thread to create new wiki page, where we can explain the problematics better.

All of these _grid?_ is important for creation of a grid, where the Lennard-Jones and electrostatic forcefield is pre-calculated.  In the code we do not have any automatic centring of the system, since that would actually make the things even more complicated. Even though the whole thing is pretty simple in the way it is done and in what is expect, but still it means kind narrow restriction on how the systems is supposed to be fed to PPM.

I also do not know, if your input are just atoms (and charges) or if you are using some DFT (or different electronic-structure computations) to compute the Hartree potential. I will try to accompany both possibilities:

- **First of all**, the code expects, that your system is in the cell starting in 0,0,0, given by the 3 lattice vectors - each of them is a row: **1st** is `gridA`; **2nd** `gridB` and the **last** one is `gridC` (normally 0. 0. _height of cell_ ) - basically the same strategy as in [ASE](https://wiki.fysik.dtu.dk/ase/index.html):
  - For example if your system has centre of mass at 0,0,0 you can run into problems (sometimes problem with FHI-aims).
  - Or if your geometry is bellow 0 in _z_ then the atoms are not captured properly, regardless of stated `PBC` or `nPBC`. 
  - it is also good practise to leave enough space above the top-most atoms in the _z_ direction: 15 Angstrom is pretty safe.
  - which leads to another good practise to shift the system to a lower part of your cell.
- **If you are using hartree potential (xsf or cube files)**; Then you do not need to care about these - the points of the grid are exactly the same as in those file with potential.
   - If you want better (more dense) spacing or larger cell, then you need to redo you DFT calculations with adjusted parameters
- **If not -- you have to specify:** `gridA` , `gridB` and `gridC` by hand (default values do not make any sense):
   - if you have system that is periodic in _x_ and _y_ (surface) than adjust `gridA` and `gridB` with the exact lattice vector; `gridC` needs to have enough space about the atoms (as mentioned above).
   - If you have something like molecule or 1D nano-ribbon leave there like 10 angstrom of free space in every direction, to have enough space between periodic images.
-  `gridN` sets the amount of points in each direction; Normally you do not need to specify and it is the best to comment this option. this as it gives automatic spacing of approx. 0.1 , so gridN _a_ = int(norm(gridA)*10)  ... ;
   -  if you want to play with with `gridN`, like to have more denser grid, then put there amount of points in each vector given by gridA ... 
 

As I am trying to think of the possible problems, I am maybe not answering your questions. Maybe if you would be more specific, what you want and attach the system what you qnt to calculate, then I could help you more.

**Comment by ondrejkrejci** [comment]
Wiki updated.
